# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=datetime.date(2016, 3, 11)),
        ),
    ]
