"""empty message

Revision ID: 3dd3210c2b16
Revises: None
Create Date: 2016-02-08 09:58:31.648300

"""

# revision identifiers, used by Alembic.
revision = '3dd3210c2b16'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
